### ISSUE TITLE
Any plans for official release

### ISSUE THREAD

**Issue by georgepapas** [sszuev/fastText_java#2]
Hi there, 

Is there a roadmap for an non snapshot release into jitpack or other maven repo?

Cheers
George

**Comment by sszuev** [comment]
Hello. 
Unfortunately, right now I can't continue work closely on fastText_java, only occasionally, and there is no concrete roadmap.
But making a maven release is not at all difficult, and, perhaps, it is worthwhile to do it.
I just care about how justified it is?
It seems, after your fix there should not be a problem with jitpack,
The original fasttext trains models faster than this version (although I tested it on a virtual machine with only one CPU).
There were also ideas about MapReduce (but no clarity, since the original fasttext uses the same matrix in multithreding)

**Comment by georgepapas** [comment]
Hi, 

The use case I have is using this library not for training models, but for reading fast text models from a jvm based api. Might be nice to have a 1.0.0 release.

**Comment by sszuev** [comment]
v 1.0.0 provided : https://search.maven.org/#search%7Cga%7C1%7Cg%3A%20%22com.github.sszuev%22%20a%3A%20%22fasttext%22
