### ISSUE TITLE
OOV

### ISSUE THREAD

**Issue by ali3assi** [sszuev/fastText_java#5]
Hello,

I want to use your version of fasttext in my poject, but i want to check before if this version handle the OOV words.  

Thank in advance for your confirmation on how your code deals with the OOV during test phase
Regards

**Comment by sszuev** [comment]
Please note: this java fasttext reflects only that version of the original [fasttext cpp version](https://github.com/facebookresearch/fastText), which is mentioned in Readme.
So to get answered your question you have to answer the following two questions:
- does the cpp version supports OOV ?
- does the cpp version, that have been released in December 2017, supports OOV ?

About cpp fasttext and OOV I found this answer: https://stackoverflow.com/questions/48017343/how-to-convert-gensim-word2vec-model-to-fasttext-model/48029141#48029141

Hope this helps.

By the way, I am not sure that some opinion or answer to some question are sufficient enough to make a decision about including or not some library into your project.
I think you better to check all of candidate-libs by yourself, including functionality that you need, performance and etc.
As for this project - since December 2017 I still have no time to support it fully and to work on continuous reflection any changes in the cpp version. Sorry.
